services:
    # Backend API
    smart-brain-api:
        container_name: backend
        # image: node:16.17     # we don't need it since we will build from the Dockerfile that image
        build: ./
        command: npm run start:dev
        working_dir: /usr/src/smart-brain-api
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
            # REDIS_URI: redis://redis:6379
        ports:
            - "3000:3000"
        volumes:
            - ./:/usr/src/smart-brain-api

    # Database
    postgres:
        # container_name: postgres
        build: ./postgres
        restart: always
        environment:
            POSTGRES_USER: sally
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker
            POSTGRES_HOST: postgres
        ports:
            - "5432:5432"

    # Redis
    redis:
        image: redis
        ports:
            - "6379:6379"
